import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const rubik = localFont({
  src: "../../public/fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-rubik",
  display: "swap",
});

const inter = localFont({
  src: "../../public/fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  display: "swap",
});

const arial = localFont({
  src: "../../public/fonts/arial.ttf",
  variable: "--font-arial",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Shop Meichu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${inter.variable} ${arial.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
