import type { Metadata } from "next";
import { Inter, Rubik, Outfit } from "next/font/google";
import "../styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar/navbar";

const rubik = Rubik({
  variable: "--font-rubik"
});

const inter = Inter({
  variable: "--font-inter",
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shop Meichu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${inter.variable} ${outfit.variable} antialiased`}
      >
        <Navbar />
        <main className="pt-16 pb-16 sm:pb-0">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
